name: Email Step Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3000857@ds.study.iitm.ac.in
        run: echo "Hello, world! This step includes my email in its name."
